### ISSUE TITLE
Throw specialized error for constraint violations

### ISSUE THREAD

**Issue by twistedstream** [twistedstream/google-sheets-table#37]
Throw a more specialized `Error` object when [constraint violations occur](https://github.com/twistedstream/google-sheets-table/blob/5d7bed59f6af9c7187807db854255904eb7bf276/src/table.ts#L61) so that client code can detect it without having to parse the error `message`, which is more fragile.

So instead of having to do this:

```js
try {
  const { insertedRow: user } = await table.insertRow(newRow);
  // do something with insertedRow
  ...
} catch (err) {
  if (err.message.includes("A row already exists with")) {
    // handle constraint violation
  }
}
```

you can do this:

```js
try {
  const { insertedRow: user } = await table.insertRow(newRow);
  // do something with insertedRow
  ...
} catch (err) {
  if (err instanceof ConstraintViolationsError) {
    // handle constraint violation
    if (err.violations.some(v => v.type === "unique")) {
      ...
    }
  }
}
```

This enhancement proposes adding a `ConstraintViolationsError` class with a `violations` property that returns an array of `ConstraintViolation` objects. Each violation object would have a `type: string` and a `description: string` property.

**Comment by wovasteenGova** [comment]
I definitely like the second version better!
